name: NovaPay CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Application
        run: echo "Building NovaPay"

      - name: Run Unit Tests
        run: echo "Running Tests"

      - name: Security Scan
        run: echo "Running Security Checks"

      - name: Deploy
        run: echo "Deploying"